version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
    restart: unless-stopped
    ports:
      - "3000:3000" 